- hosts: aws
  become: true
  tasks:
    - name: Install firewalld if not already installed
      package:
        name: firewalld
        state: present
      ignore_errors: true

    - name: Start firewalld service
      service:
        name: firewalld
        state: started
      ignore_errors: true

    - name: Open ports in firewalld
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
        immediate: true
      loop: "{{ ports }}"

    - name: Check for directory existence
      stat:
        path: /var/www/html/www.companyplus.com
      register: directory_check

    - block:
        - name: Directory exists
          debug:
            msg: "/var/www/html/www.companyplus.com exists"
      when: directory_check.stat.exists

    - block:
        - name: Directory does not exist
          debug:
            msg: "/var/www/html/www.companyplus.com does not exist"
          failed_when: true
      when: not directory_check.stat.exists

    - name: Install nginx
      package:
        name: "{{ webserver }}"
        state: present

    - name: Create directories
      file:
        path: "{{ item }}"
        state: directory
        owner: nginx
        group: nginx
        mode: '0770'
      loop:
        - /var/www/html/www.companyplus.com
        - /var/www/html/www.companypulsar.com

    - name: Template nginx configuration
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
      notify: restart nginx

    - name: Start nginx service
      service:
        name: "{{ webserver }}"
        state: started
        enabled: true

  handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted
