---
- name: Install nginx
  package:
    name: "{{ webserver }}"
    state: present

- name: Create website directories
  file:
    path: "{{ item }}"
    state: directory
    owner: nginx
    group: nginx
    mode: '0770'
  loop:
    - /var/www/html/www.companyplus.com
    - /var/www/html/www.companypulsar.com

- name: Template nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Start and enable nginx service
  service:
    name: "{{ webserver }}"
    state: started
    enabled: true
